# 1.3.1

In [19]:
import numpy as np

matrix = np.arange(64).reshape(8, 8)

matrix = np.zeros((8, 8), dtype = int)

matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 1.3.2

In [28]:
import numpy as np

matrix = np.arange(25).reshape(5, 5)
matrix[1::1] = np.arange(0, 5)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3

In [103]:
import numpy as np
import random as rand

matrix = np.random.random((3, 3, 3))

print(matrix)

[[[0.81353745 0.68515286 0.28304626]
  [0.33690559 0.63203985 0.43277221]
  [0.12934207 0.3576694  0.8537017 ]]

 [[0.66216924 0.35346177 0.12353998]
  [0.00355468 0.80344772 0.19433714]
  [0.52903176 0.31388897 0.03736138]]

 [[0.6439907  0.68847996 0.23645346]
  [0.84606599 0.35118245 0.30557938]
  [0.54693252 0.27218232 0.45727232]]]


# 1.3.4

In [139]:
import numpy as np

matrix = np.ones((10,10), dtype = int)
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


# 1.3.5

In [137]:
import numpy as np

array = [0, 1, 2, 3, 4, 5]
array.sort(reverse=True)
print(array)


[5, 4, 3, 2, 1, 0]


# 1.3.6

In [4]:
import numpy as np

matrix = np.zeros((10,10), dtype = int)
print("square")
print(matrix.size)
print(matrix.shape)

square
(10, 10)
100


# 2.3.1

In [ ]:
import numpy as np

point1 = np.array((1, 1, 1))
point2 = np.array((5, 5, 5))

square = np.square(point1 - point2)
sumSquare = np.sum(square)

print(np.sqrt(sumSquare))

# 2.3.2

In [142]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'

dataFrame = pd.read_csv(url)
dataFrame.head(5)

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Other    Male              40   
4     Prof-specialty           Wife  Other  Female              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K  
4          Other        0         <=50K

# 2.3.3

In [151]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'

dataFrame = pd.read_csv(url)
dataFrame.head(2)

age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K

In [152]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'

dataFrame = pd.read_csv(url)
dataFrame.tail(3)

age     workclass  education_num      marital_status       occupation  \
45219   38       Private             13  Married-civ-spouse   Prof-specialty   
45220   44       Private             13            Divorced     Adm-clerical   
45221   35  Self-emp-inc             13  Married-civ-spouse  Exec-managerial   

      relationship   race gender  hours_per_week native_country  capital  \
45219      Husband  White   Male              50  United-States        0   
45220    Own-child  Other   Male              40  United-States     5455   
45221      Husband  White   Male              60  United-States        0   

      income_status  
45219         <=50K  
45220         <=50K  
45221          >50K

In [153]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'

dataFrame = pd.read_csv(url)
dataFrame.shape

(45222, 12)

In [154]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'

dataFrame = pd.read_csv(url)
dataFrame.describe()

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [155]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'

dataFrame = pd.read_csv(url)
dataFrame.iloc[1:4]

age         workclass  education_num      marital_status  \
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   

          occupation   relationship   race gender  hours_per_week  \
1    Exec-managerial        Husband  White   Male              13   
2  Handlers-cleaners  Not-in-family  White   Male              40   
3  Handlers-cleaners        Husband  Other   Male              40   

  native_country  capital income_status  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K

In [159]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'

dataFrame = pd.read_csv(url)
dataFrame[dataFrame['gender'] == 'Male'].head(4)

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   

          occupation   relationship   race gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White   Male              40   
1    Exec-managerial        Husband  White   Male              13   
2  Handlers-cleaners  Not-in-family  White   Male              40   
3  Handlers-cleaners        Husband  Other   Male              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K

# 3.3.2

In [180]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataFrame = pd.read_csv(url)
value_array = np.array(dataFrame['sepal_length_cm'])
normalized_array = preprocessing.normalize([value_array])
print(normalized_array)
print(round(value_array.mean()))
print(value_array.std())

[[0.07056264 0.06779548 0.06502832 0.06364474 0.06917906 0.07471338
  0.06364474 0.06917906 0.06087757 0.06779548 0.07471338 0.0664119
  0.0664119  0.05949399 0.08024771 0.07886413 0.07471338 0.07056264
  0.07886413 0.07056264 0.07471338 0.07056264 0.06364474 0.07056264
  0.0664119  0.06917906 0.06917906 0.07194622 0.07194622 0.06502832
  0.0664119  0.07471338 0.07194622 0.07609697 0.06779548 0.06917906
  0.07609697 0.06779548 0.06087757 0.07056264 0.06917906 0.06226115
  0.06087757 0.06917906 0.07056264 0.0664119  0.07056264 0.06364474
  0.0733298  0.06917906 0.09685068 0.0885492  0.0954671  0.07609697
  0.08993278 0.07886413 0.08716562 0.06779548 0.09131636 0.07194622
  0.06917906 0.08163129 0.08301487 0.08439845 0.07748055 0.09269994
  0.07748055 0.08024771 0.08578203 0.07748055 0.08163129 0.08439845
  0.08716562 0.08439845 0.0885492  0.09131636 0.09408352 0.09269994
  0.08301487 0.07886413 0.07609697 0.07609697 0.08024771 0.08301487
  0.07471338 0.08301487 0.09269994 0.08716562 0.0

In [166]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataFrame = pd.read_csv(url)
minMax_scale = preprocessing.MinMaxScaler()
dfTest = dataFrame
dfTest[['sepal_width_cm']] = minMax_scale.fit_transform(dfTest[['sepal_width_cm']])
print(dfTest)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1        0.625000              1.4             0.2   
1                4.9        0.416667              1.4             0.2   
2                4.7        0.500000              1.3             0.2   
3                4.6        0.458333              1.5             0.2   
4                5.0        0.666667              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7        0.416667              5.2             2.3   
146              6.3        0.208333              5.0             1.9   
147              6.5        0.416667              5.2             2.0   
148              6.2        0.583333              5.4             2.3   
149              5.9        0.416667              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 